# Generated by Django 4.2.9 on 2024-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Basketball', 'Basketball'), ('Badminton', 'Badminton'), ('Volleyball', 'Volleyball')], max_length=20)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged')], default='Good', max_length=20)),
                ('tag_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
