# Generated by Django 4.2.9 on 2024-03-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemcopy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCopy',
        ),
    ]
