# Generated by Django 4.2.9 on 2024-03-28 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_delete_itemcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('borrow_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.itemtag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemUnreturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unreturn_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_unreturn', to='items.itemborrow')),
            ],
        ),
        migrations.CreateModel(
            name='UnreturnToReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unreturn_item_to_return', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_return', to='items.itemunreturn')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_returned', models.DateTimeField(auto_now_add=True)),
                ('return_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_return', to='items.itemborrow')),
            ],
        ),
    ]
