# Generated by Django 4.2.9 on 2024-03-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemborrow_itemunreturn_unreturntoreturn_itemreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreturn',
            name='return_item',
        ),
        migrations.RemoveField(
            model_name='itemunreturn',
            name='unreturn_item',
        ),
        migrations.RemoveField(
            model_name='unreturntoreturn',
            name='unreturn_item_to_return',
        ),
        migrations.DeleteModel(
            name='ItemBorrow',
        ),
        migrations.DeleteModel(
            name='ItemReturn',
        ),
        migrations.DeleteModel(
            name='ItemUnreturn',
        ),
        migrations.DeleteModel(
            name='UnreturnToReturn',
        ),
    ]
