# Generated by Django 4.2.9 on 2024-03-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreturn',
            name='return_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_return', to='transactions.itemborrow'),
        ),
        migrations.AlterField(
            model_name='itemunreturn',
            name='unreturn_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_unreturn', to='transactions.itemborrow'),
        ),
    ]
