# Generated by Django 4.2.9 on 2024-03-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_itemreturn_return_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreturntoreturn',
            name='unreturn_item_to_return',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_return', to='transactions.itemunreturn'),
        ),
    ]
